/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-21-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global with sharing class CustomContactsCounter {

    public List<CustomContact> i_miei_custom_contact;
    public Integer numero_contact;
    
    public CustomContactsCounter() {

    }
}